### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rea987** [shinyquagsire23/OpenJKDF2#10]
I have requested the port to be added to Luxtorpeda repo whose developer asked about licence of OpenJKDF2. Can the license info be added please? Thanks!

https://github.com/luxtorpeda-dev/packages/issues/576

https://github.com/luxtorpeda-dev/luxtorpeda#luxtorpeda-dev

**Comment by shinyquagsire23** [comment]
I've added a LICENSE.md, it's a 0-clause BSD license with some additional disclaimers around trademarks, and the commercial-use clause is removed because I can't really grant that. That's probably about as much as I can clarify on licenses because like most reverse-engineered projects, it's all very gray legally.
