### ISSUE TITLE
Contain cutscenes to 16x9

### ISSUE THREAD

**Issue by fathutt** [shinyquagsire23/OpenJKDF2#104]
Cutscenes on ultrawide monitors are stretched horizontally and had top and bottom cut off. It would be better to stretch them vertically and have black bars on the sides.

**Comment by shinyquagsire23** [comment]
Fixed (aab85df18bddd8042a1921c6c594c938fd348f3e), the new behavior is if the monitor is greater than 21:9, it will constrain to the center 16:9 portion of the screen. That way 21:9 ultrawide monitors don't needlessly get black bars where they would otherwise perfectly fit the content, but 32:9 and triple 16:9 setups will just limit themselves to the center 16:9 portion of the displays.

**Comment by shinyquagsire23** [comment]
Fixed v0.6.9

**Comment by fathutt** [comment]
So, it now has black bars on top and on bottom) I mistakenly thought that cutscenes is 16:9 ratio, but I guess it's actually 21:9.
![image](https://user-images.githubusercontent.com/7819980/194941512-7dfd362f-59ea-4f8e-a18f-7f7b8d1cea80.png)

**Comment by shinyquagsire23** [comment]
Yeah it's ~slightly under 21:9 iirc, but the expectation is more or less that there's always bars at the top/bottom that get used for the subtitles and pause text, same as the original game on 4:3. I'd ~rather not add heuristics stretching it vertically only because it would look exceptionally weird at 4:3, and my own monitor is 16:10.
