### ISSUE TITLE
Volume sliders reset when game is closed

### ISSUE THREAD

**Issue by JordanRadar** [shinyquagsire23/OpenJKDF2#133]
The music is deafening by default, so I tend to turn it down after launching. However, the values of the sliders don't seem to save anywhere, so the music is back to max volume when I relaunch. (This may be a known issue to those with ears.)

**Comment by shinyquagsire23** [comment]
Fixed, 2ca2a50dcad390b31f4a6a25065b5255dd5fce2f and 7c160408b450199269a5774f61b6e08b1d4683ed, to be included in next release

For now I just tied cutscene audio to the music volume since that's the safest bet for like, streaming and avoiding DMCAs. But I'll probably give it its own slider in a day or so.

**Comment by shinyquagsire23** [comment]
Fixed [v0.6.16](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.6.16)
