### ISSUE TITLE
MOTS - Cheats are incorrect

### ISSUE THREAD

**Issue by JordanRadar** [shinyquagsire23/OpenJKDF2#134]
The normal MOTS cheats don't appear to work while playing MOTS, but the DF2 cheats do. The slowmo cheat also appears to be broken as well.

**Comment by linusrachlis** [comment]
I was just doing some investigation into `slowmo` in particular. It was one of my fav cheats, because I love how it turns action tactics more into strategy. The game can be punishing on hard, but going slowmo is a way to make the challenge more manageable in a way that's interesting rather than cheap and boring. It's like force speed, but for thought :)

I have no real experience with this type of programming, but it seemed like a good opportunity to learn.

(TL;DR of the below is that typing `slowmo 1` sets a debug flag bit, but I couldn't find anywhere that is checking for that particular bit in the debug flags value. Maybe that's why slowmo doesn't work, but I don't know why nothing is checking for it. Maybe that code hasn't been decompiled yet, so I can't search for it?)

---

I saw that the `slowmo` command is created by `jkDev_RegisterCmd` here:
https://github.com/shinyquagsire23/OpenJKDF2/blob/9f7dc1e5b0cf2152004a13e8c6c3da10f0be333f/src/Main/jkDev.c#L57

The handler for the slowmo command is `jkDev_CmdDebugFlags3`. (For some reason, there is also `jkDev_CmdDebugFlags2` and `jkDev_CmdDebugFlags` which look identical to me.) These functions are used to handle various other commands `whiteflag` (disable AI) and `jediwannabe` (god mode), depending on what `extra` arg is passed (7 for slowmo).

`sithCommand_CheatSetDebugFlags` seems to be what does the real work setting the debug flags:
https://github.com/shinyquagsire23/OpenJKDF2/blob/d6147d329223cdb24087f27c1904bdfd1f6df3f5/src/Main/sithCommand.c#L80

There is a switch based on that "extra" value. Depending on the value, a different bit will be flipped on or off in a global var, `g_debugmodeFlags`, unless the extra value was 1, in which case the target for bit flipping will be `sithRender_flag`, or 5, in which case the target will be the player actor's flags (which makes sense for god mode).

(This switch statement has a weird way of reusing the logic to set the flags by jumping to a label within the `5` case. Maybe this is sort of an artifact of the decompilation process, like the logic was inlined though it was maybe was a function in the original source? Decompilation is mostly a mystery to me currently.)

Anyway, under `case 7u` for slowmo, I see it's setting the 0x400 bit to the flags value:
https://github.com/shinyquagsire23/OpenJKDF2/blob/d6147d329223cdb24087f27c1904bdfd1f6df3f5/src/Main/sithCommand.c#L151-L154

However, I don't see this value being checked for anywhere.

Just to check my method, I looked for other checks of the flags. The AI code is littered with `if (g_debugmodeFlags & 1)` checks ([example](https://github.com/shinyquagsire23/OpenJKDF2/blob/e80708d691a1f4afc4abdb3236a5c591b334cca2/src/Cog/sithCogFunctionAI.c#L47)), which makes sense since the flags value's first bit is used for the "disable AI" mode:
https://github.com/shinyquagsire23/OpenJKDF2/blob/d6147d329223cdb24087f27c1904bdfd1f6df3f5/src/Main/sithCommand.c#L94-L97
("extra" value = 0 for that command)
https://github.com/shinyquagsire23/OpenJKDF2/blob/9f7dc1e5b0cf2152004a13e8c6c3da10f0be333f/src/Main/jkDev.c#L52

So, it seems like I should also be able to find `g_debugmodeFlags & 0x400` or the equivalent, `g_debugmodeFlags & 1024` somewhere. Even searching for all usage of `g_debugmodeFlags`, I don't see anything that might be checking for the 0x400 bit and none of it looks like the deep physics/gameplay/timing code I would expect to be involved with this flag.

I don't know if this means the flag is just being ignored (so, makes sense slowmo doesn't work), or it is being checked somewhere, but the code checking for it has not been decompiled yet -- in which case maybe the reason it doesn't work is more subtle.

From looking at the readme, it seems like most of the as-yet-not-decomped code is the rasterizer, and assuming I understand correctly what that is, it's not a system I'd expect to care about slowmo mode.

---

This is my first post on this project, just want to say playing JK again has brought me a lot of joy, and getting to browse its source code (or at least similar source code) for a game I loved over two decades ago has been a lot of fun. Thanks for the hard work!

**Comment by Journeyman716** [comment]
Now fixed as of 0.7.9

**Comment by Vortikai** [comment]
Tested both DF2 and MotS on v0.7.10, fixed. I think this could be closed now.

**Comment by shinyquagsire23** [comment]
Yep definitely fixed but I forgot the version
