### ISSUE TITLE
Horizontal mouse movement is improperly interpolated

### ISSUE THREAD

**Issue by Goofbaal** [shinyquagsire23/OpenJKDF2#139]
There's a similar bug in the vanilla game. Mouse movement polls independently from the framerate: Geometry, characters, and particles appear smooth at any framerate, but the camera moves at what appears to be 60hz. This quirk only affects the X Axis.

**Comment by shinyquagsire23** [comment]
Hmmm, the original game one was because physics were ticked at 50Hz and the mouse only applies angular acceleration to the player Thing, but I set physics to tick at 150Hz now so I would have thought it ticks faster.

I have noticed in MoTS the scope zoom is weirdly quantized though (can't fine-tune the aim), I suspect that might create something that looks like a 60Hz update.

**Comment by Goofbaal** [comment]
I was wrong! 
Using a Framerate Monitor, I discovered that OpenJKDF2's mouse movement wasn't the problem. Running the game in Fullscreen caps the framerate at 100hz, leading to jitterier camera movement overall. Running in Windowed Mode solves this problem. More below:

https://github.com/shinyquagsire23/OpenJKDF2/issues/147#issue-1512302431

**Comment by rickomax** [comment]
Necro this bc I've discovered playing the game without vsync causes the same issue here in latest debug version
