### ISSUE TITLE
Level start confirmation menu option

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#179]
#135 requested a confirmation to begin a level as modern PCs allow loading so fast it skips the level description. That's a wonderful enhancement. The menu option has a period at the end of the string that is inconsistent with other menu options.

I also believe the default should be how it was in the vanilla games, with the option being opt-in, but that's not a big deal/up to you.

**Comment by shinyquagsire23** [comment]
Oh yeah there's already an option under Setup > General, "Disable mission start confirmation". I kinda debated on the defaults but erred on the side of 'the mission text was meant to be read, and playing through MoTS the first time without it was confusing' lol

**Comment by shimstock22** [comment]
I think I tend to agree with Vortikai, though I could honestly care less what you choose is best. However, my reasoning is my pc still loads slowly enough for me to read the mission debriefings. Second, this could be a surprise for someone new to the project that expects the mission to start right after loading. Lastly since it is an enhancement feature, it probably does make more sense that you may choose to enable it rather than it being the default.
The only thing I go back and forth with is, rather than clicking "Ok" when ready, it may make more sense if it said "Begin" or "Begin Mission" or "Start" or "Start Mission."  Ok indicates to me that you are selecting an option and "okaying" it. 
I can only imagine how it feels for people to nit-pick. lol

**Comment by shinyquagsire23** [comment]
IIRC what I did to pick "OK" was look at the original Dark Forces pre-level mission stuff. But also I'd rather avoid adding extra localization stuff because one of my TODO items is to make all of my added strings localizable, which they currently aren't lol.

**Comment by Vortikai** [comment]
Basically this ticket is about the current iteration having a period at the end of the menu option string in jkGUIGeneral.c at line 59.

"Disable mission start confirmation.",
should be
"Disable mission start confirmation"

Of course this changes once you start localizing these strings/convert it to a key

**Comment by shinyquagsire23** [comment]
Fix staged for v0.9.5
