### ISSUE TITLE
General -> Advanced Settings not remembered

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#192]
**MotS:**

Setup -> General -> Disabled cutscene is saved as a setting across player profiles. That's good and all, but compare it to the Advanced menu, it's inconsistent.

Setup -> General -> Advanced -> Disable corpse despawining and disable physics stepping are not saved across user profiles. Additionally, disable corpse despawning seems to reset when restarting MotS to the default disabled.

**JKDF2:**
Setup -> General -> Disabled cutscene is saved per player profile.
Setup -> General -> Advanced -> Disable corpse despawining and disable physics stepping has corpse despawning saved across all user profiles, and disable physics not.

Disabled corpse despawn is reset upon restarting JKDF2 just like in MOTS.

Also is there a point to disabling physics stepping? I am not sure why one would select this option.

Steam installation. v0.7.11

**Comment by shinyquagsire23** [comment]
> Also is there a point to disabling physics stepping? I am not sure why one would select this option.
 
Speedrunners who might want the original physics, but also there was one person who reported "microstuttering" with the 150Hz ticked physics. I personally haven't been able to measure it though and I don't really have a good eye for microstutters except maybe in VR.
 
 Which like, the 150Hz ticked physics is technically going to be more "stated" than the variable-timestep physics because ~entropy and fewer possible positions, but it's literally the only way to have physics that are consistent and MP-able. And it's kinda the standard for literally every FPS.

**Comment by shinyquagsire23** [comment]
Fixed v0.7.12
