### ISSUE TITLE
(Solved in v0.9.0)Poor framerate on higher resolutions/fullscreen(Also breaks console graphics)

### ISSUE THREAD

**Issue by vincentizee** [shinyquagsire23/OpenJKDF2#253]
Been trying to get this to run well for days and sorry if this is not a very technical description.

When in windowed mode (starting resolution is something like 640x300 according to the debug window) I get ~140 fps, which is great but as soon as I go to fullscreen the fps goes to 45-55. The only way I can play this in fullscreen is to lower my screen resolution in windows to 800x600 so that the upscaling won't drastically affect the performance. 

I'm on a gtx 1080 on Win10, this issue seems to be constant and nothing to do with my pc.
Is there a way to force the amount of scaling performed so that I don't have to break my windows every time I want to try to play the game(albeit in potato resolution).
Everything is vanilla settings except for 144 fps cap. 
![55fps](https://user-images.githubusercontent.com/60829146/228410861-a97bef39-d48a-40e1-b370-a159870730fb.jpg)
![140fps](https://user-images.githubusercontent.com/60829146/228410865-2d123ebd-debf-4b59-bd67-1e4d6c7ec5b2.jpg)

**Comment by shinyquagsire23** [comment]
You can change the internal framebuffer resolution by modifying the SSAA multiplier (ie, 0.5 would render at half resolution), my SSAO impl isn't the greatest so I usually have to keep it around 0.7 at 4Kish if I have SSAO/bloom on.

40fps on a 1080 feels kinda off though, and the console graphics breaking is definitely a bug

**Comment by vincentizee** [comment]
Changing the multiplier does change the resolution for me but not the framerate. I tried all the way down to 0.1 multiplier and although it looks great, I don't get any performance increase. It's like the size of the window automatically determines the performance for me. I can drag a windowed virseon of the game down and get more fps and I can drag it up to get less.
![jkdf2 01 ssaa](https://user-images.githubusercontent.com/60829146/229000220-cfb23f6d-bc33-4762-8923-d5298e04ebc4.jpg)

**Comment by Biggs-Hoson** [comment]
I've got the exact same problem on 2 PCs.
~70fps on a R7 5800H, RTX 3060 laptop
~90fps on a R9 5900X, GTX 960 desktop
Scales with the window size, no settings seem to solve the performance issue. Interestingly, the performance seems to improve when going to the better CPU and worse GPU.
Hope this helps.

**Comment by rgstoian** [comment]
Same problem here, game runs at around 40FPS regardless of graphics settings.
CPU: Intel i5 6600k
RAM: 24GB DDR4
GPU: GTX 1070 8GB

**Comment by Havner** [comment]
What's your SSAA multiplier? I have 4080 and anything above 2 kills the FPS drastically. Like several orders of magnitude more than it should. Even on 2.0 I barely have 60fps in 4K. That the biggest fps killer I've found in OpenJKDF2.

**Comment by shinyquagsire23** [comment]
the good news is that I noticed in testing yesterday that my Win11 Parallels VM has the same issue, which is ~interesting because Parallels passes through macOS OpenGL directly, and macOS hasn't had this issue. So I should at least be able to debug and A/B test things pretty easily.

I'm hoping I won't have to tie SSAA into Windows/SDL APIs because I was planning on adding a resolution selection box or something soon but idk, as it is it doesn't seem to function correctly on Windows

**Comment by rgstoian** [comment]
I don't think it's SSAA related, I'm getting the same performance in full-screen with it set to 0.5 or 1.0, also with HIDPI on or off on a 4k display.

**Comment by shinyquagsire23** [comment]
This might be fixed in v0.9.0?

**Comment by rktjmp** [comment]
Fixed it on my Linux64-SDL build.

**Comment by raleesound** [comment]
@shinyquagsire23 This looks like it was fixed with v0.9.0 for me. I have noticed that the SSAO and Bloom impact performance heavily when used in conjunction with SSAA, but I am now able to run it in 1440p locked at 144fps on my 6700k/980Ti rig. From there, I can either enable SSAO and bloom and maintain my FPS, _or_ I can set SSAA to 2.0 without losing perf, but if I put the two together I get 36 FPS.

But I'm really just adding that last bit in case the data is helpful to you, I would definitely consider this issue resolved from my end. Awesome work on this project!

**Comment by shinyquagsire23** [comment]
@raleesound yeah that's more or less the expected performance behavior, on my M1 MBP it's like 200+FPS with vanilla rendering, but with both SSAO/bloom on I have to set it to 0.7x res in order to keep 60+ FPS. My implementation definitely needs work but part of it is just legacy engine crust (all the camera transformations are still done on CPU for example)

The fact that *resolution* was significantly *CPU* limited is slightly concerning though and makes me think that maybe there's some extra FPS to be eeked out if I can find which function is causing issues. But at least all platforms are to the same point performance-wise now lol
