### ISSUE TITLE
WebAssembly version showing a black screen

### ISSUE THREAD

**Issue by lrusso** [shinyquagsire23/OpenJKDF2#316]
Hello, congratulations for such a great project! I just tried the MacOS port and it works great. I just wanted to report that the WebAssembly version is not working (it's showing a black screen). I tried using the latest Chrome and Firefox versions on MacOS (14.4.1).

https://maxthomas.dev/openjkdf2/

**Comment by lrusso** [comment]
Found the reason, the JavaScript code is expecting arguments, it works when browsing to https://maxthomas.dev/openjkdf2/?windowGUI

Maybe the README.md should be showing the right URL or the JavaScript logic should be adjusted.

**Comment by queenkjuul** [comment]
Can you tell me how you built the wasm version? I've been trying with no luck on ubuntu 24.04. It builds just fine, but I get problems when I run it, even with the `?windowGUI` param

I had to make a couple tweaks just to get it to build. Then I get file errors in the browser. `mayCreate` in `openjkdf2.js` always returns `20`. If I comment that out, I get this:
`FATAL ERROR: ERR_CANNOT_LOAD_FILE ui\sft\small0.sft 127.0.0.1:8080:151:21`

Otherwise I get a generic error 44, which `node_ops.lookup` does no matter what. So I don't understand what's going wrong. The filesystem isn't getting set up right. 

Having dug around the code so much though, I think I see how I could fix the URL param / argument error problem, if I could get the project to work in the first place.

**Comment by shinyquagsire23** [comment]
I think I fixed this a while back
