### ISSUE TITLE
Questions!! Questions!! Questions!!

### ISSUE THREAD

**Issue by darkstar252** [shinyquagsire23/OpenJKDF2#341]
The program is able to play the music tracks on mp3 in a folder ./music from the game folder, like yamagi quake2?

There is a wiki on the github page about the program , basically for new upcommers on how to install compile how to put the music etc?

There is a discord channel?

**Comment by SeongGino** [comment]
All the installation and build instructions are already laid out for you on a silver platter in the README.

**Comment by shinyquagsire23** [comment]
Yeah the general recommendation if you need a super simple install process is to buy the GOG version and then replace JK.EXE with OpenJKDF2, and it'll just work. Otherwise yeah, check the readme for examples, at some point I'd like to add CD parsing for the music so that I can have it done in one swoop with the first-time installation, but that's fairly involved unfortunately.
