### ISSUE TITLE
Request: aspect ratio correction/widescreen support?

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#35]
Seems this supports adjusting resolution on the fly by resizing the window, which is a great step in the right direction. However, right now, anything other than 4:3 stretches things to oblivion, which gets very disorienting. Would it be feasible to get some form of aspect correction/widescreen support?

Also, unreleated: What is HiDPI mode? Can't tell a difference when turning it on.

**Comment by shinyquagsire23** [comment]
So, the odd thing is that I *have* aspect ratio correction (https://github.com/shinyquagsire23/OpenJKDF2/blob/master/src/Engine/sith.c#L327) and it's actually pretty noticeable with weapons in particular (on the original game, 16:9 screens will barely draw the weapon). The original game actually used a 1:1 aspect ratio for everything.

I also have https://github.com/shinyquagsire23/OpenJKDF2/blob/master/src/World/jkPlayer.c#L413 so that weapons look ~roughly the same between 16:9 and 4:3, with the FoV adjusted accordingly. Without that adjustment, 
[this is what 4:3 corrected looks like](https://user-images.githubusercontent.com/1224096/144641264-b8233e80-1344-4040-b12f-3264c0e3f149.png), and [this is what 16:9 corrected looks like](https://user-images.githubusercontent.com/1224096/144641181-46ae7278-6f50-4c47-8d0c-d656144fb6ce.png). I think at some point I'm just going to add a TF2-style cvar console with all the rendering constants so that everyone can just tweak to their own tastes, instead of having a bunch of weird options in menus.

But yeah 16:9 will squish only because the hFOV is set to 90 degrees, I think the equivalent hFOV is 106. I might end up adding a FoV-is-4:3-equivalent flag so that it can autoscale.

Re:HiDPI, HiDPI is mostly for newer MacOS machines, and I think it might also apply to Windows machines with 4K monitors. It prevents the OS from only rendering the window at half-resolution.

**Comment by StrikerMan780** [comment]
![image](https://shadowmavericks.com/files/ShareX/openjkdf2-64_2021-12-03_19-27-01.png)
Just to give you an idea of what I'm referring to. Even after adjusting the FOV accordingly, everything is heavily stretched horizontally, with exception of HUD elements.

**Comment by shinyquagsire23** [comment]
Hmmm ok actually yeah you're definitely correct, now that I'm looking at it. On MacOS if I resize the window to half-height while it runs, I'd expect the vertical FOV to get halved, but the horizontal FOV to stay the same. But instead, the vertical FOV remains the same.

**Comment by shinyquagsire23** [comment]
OK so this is the latest commit, here's before:
![aspect before](https://media.discordapp.net/attachments/470665255777861634/918335785411948544/before-aspect.png)

and after:
![aspect after](https://media.discordapp.net/attachments/470665255777861634/918335816076517426/after-aspect.png)

Horizontal FOV remains consistent, but vertical crops properly instead of stretching.

**Comment by shinyquagsire23** [comment]
Fixed, [v0.1.20](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.1.20)

**Comment by StrikerMan780** [comment]
This isn't ideal. This causes Vert- widescreen. Hor+ widescreen is better.

**Comment by shinyquagsire23** [comment]
Ah, well in any case the fix I pushed is a step towards that kind of implementation. The old behavior was horizontal FOV fixed *and* the vertical FOV squashed. Might see if I can add a toggle real quick.

**Comment by StrikerMan780** [comment]
Alright, sounds good. Thanks for taking the time to do this, by the way.

**Comment by shinyquagsire23** [comment]
Alright implemented in [v0.1.21](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.1.21). I actually stumbled onto that behavior on accident so it was an easy addition.

**Comment by StrikerMan780** [comment]
The only other thing is either making it so that the slider can go lower (90 vertical is pretty zoomed out), or make it so that the number you choose is equivalent. Like, make 90 degrees FOV in 16:9 is in actuality 59 degrees vertical. This can be solved with a little bit of math.

**Comment by StrikerMan780** [comment]
Checked out the latest changes. Works great now.

There's something else that needs tackling, but it's unrelated to widescreen or the FOV (as far as I know), so I opened a new issue for that in particular.
