### ISSUE TITLE
Rendering is horizontally distorted (unrelated to FOV or widescreen)

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#36]
Here's a screenshot of the original DF2 at 640x480.
![image](https://shadowmavericks.com/files/ShareX/JK_2021-12-12_16-28-28.png)

The same area in OpenJKDF2, at the same resolution.
![image](https://shadowmavericks.com/files/ShareX/openjkdf2-64_2021-12-12_16-30-19.png)

**Comment by shinyquagsire23** [comment]
The original game uses a 1:1 aspect ratio for its vertex projection as a performance/accuracy tradeoff in order to save on an extra multiply (rdCamera_PerspProjectSquare), I guess because they assumed 4:3 was close enough. If I set the aspect ratio to 1.0, it re-distorts the same as the first picture.

I'm not really sure how to handle this as far as like, widescreen goes? But I'm sure there's at least one person who would prefer the old stretched widescreen look somehow, so I'll add this to my bucket list of graphics options to add.

Just as a side-note, the 1:1 aspect ratio seems to be something that was flip-flopped on during development. Here's a beta screenshot which used 4:3,
![image](https://user-images.githubusercontent.com/1224096/145731578-85d884e3-2154-463b-8912-f964a43a5556.png)
vs my best recreation in OpenJKDF2, 4:3
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1224096/145731593-99ee3879-ea20-4e74-8d5e-e3636214d956.png">
vs OpenJKDF2, 1:1
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1224096/145731591-630d76b8-26c3-4dd4-b1bb-9de124aaafb6.png">

At 1:1 the wide hallway opening becomes square, and looking at the tiles on the wall and under the fan, it's 4 tiles by 3.5 tiles.

**Comment by StrikerMan780** [comment]
The latter screenshot of yours is the correct behaviour. This becomes very obvious when you look at objects that are meant to be circular. In the current implementation, circles become ovals, and rectangular doorways sometimes become square.

**Comment by shinyquagsire23** [comment]
Hmmm, idk I'm still mixed on this one but I added a toggle in https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.2.1. It completely breaks the `FOV is vertical (Hor+)` option because well, the horizontal FOV and vertical FOV are already identical. I guess I could try and add a simulated 1:1 later which just squishes the horizontal FOV somehow.

**Comment by StrikerMan780** [comment]
Looks good in a 4:3 screen res now. ![image](https://shadowmavericks.com/files/ShareX/openjkdf2-64_2021-12-13_02-12-45.png)

**Comment by shinyquagsire23** [comment]
This one should be fixed as of v0.2.6, it turns out I was wrong and the original game doesn't render 1:1 like I'd thought it did. Current behavior without Hor+ enabled renders/scales identically to JK.EXE now, and enabling Hor+ works. The 1:1 option is still left there as an option but I might just remove it at some point.

**Comment by gladichl** [comment]
In which file is FOV handled in the latest version?
