### ISSUE TITLE
Some mods (Like JKE and Saber Battle X) crash OpenJKDF2 due to unknown image format.

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#61]
I know this is likely just due to missing stuff from community patches, but seems like JKE.GOB crashes OpenJKDF2.

This isn't anything particularly urgent, so obviously take your time. Thanks for all of the great stuff so far.

EDIT: Seems Saber Battle X, a mod that worked with the vanilla game crashes it as well with a similar error. (Unknown image format).

**Comment by shinyquagsire23** [comment]
So, I knew that 16bpp images would fail with my current setup, since I use shaders to handle 8bpp textures (and before, only 8bpp). I went ahead and implemented 16bpp textures properly and it ~works, but it turns out that JKE also has some other unknown additions around textures, somehow, to avoid editing the map JKLs.

Also for some reason the E-11 UVs are wonky
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1224096/147838971-0ef2f99a-27fa-4287-80e9-5c339fd5725f.png">

**Comment by StrikerMan780** [comment]
Well, on the bright side, Saber Battle X is working now!

**Comment by shinyquagsire23** [comment]
OK fixed v0.3.1
