### ISSUE TITLE
[0.3.9] Mouse sensitivity settings not working.

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#68]
Recently downloaded 0.3.9, upgrading from 0.3.1, and now it seem the mouse sensitivity settings do not work anymore. Lowering and raising it seems to have no effect.

**Comment by shinyquagsire23** [comment]
Are you using `Map directly to axis value`? I fixed a bug where if it was disabled, some fancy high-DPI mice would stair-step or behave oddly. I've never been able to use it with `Map directly to axis value` unticked though, it's always too slow.

**Comment by StrikerMan780** [comment]
Yes, as that is the default. Turning `map directly to axis value` off makes it so it is incredibly slow.

**Comment by shinyquagsire23** [comment]
Yeah I'm not sure I'm a fan of it either... though, that was the old behavior. I have to keep it ticked and at value 4. 

The bug that I had to fix though was twofold, they multiplied the mouse data by `deltaSeconds` instead of `1/deltaSeconds`, and I didn't accumulate mouse data correctly. The former caused unticking the option to decrease mouse input at high FPS, now I scale it to the 50fps sensitivity. The latter caused high refresh mice to just not work.

I might see if I can adjust the slider to have some more granular options.

**Comment by shinyquagsire23** [comment]
Should be fixed as of v0.3.10
