### ISSUE TITLE
where are save files located?

### ISSUE THREAD

**Issue by jgl280** [shinyquagsire23/OpenJKDF2#86]
Where are they? I wanted to copy my vanilla game saves over and use those.

**Comment by shinyquagsire23** [comment]
Depends on the platform. On macOS and Linux they are located in `~/.local/share/openjkdf2`, on Windows it is located at `%APPDATA%/Local/openjkdf2`, or if it is running portably, in the same directory as the assets.

I'll go ahead and add a note to the install instructions on that I think.

**Comment by QmwJlHuSg9pa** [comment]
Is the Flatpak running in "portable" mode? How do I stop it from behaving this way?

Is there a way to manually set a location for game files, rather than having them copied to the OpenJKDF2 dir?

Ideally, I want `controls/`, `player/` and `registry.json` separate from the game files. If the first issue were resolved, I could at least symlink to a mounted directory.

Thanks

**Comment by shinyquagsire23** [comment]
You can set the `OPENJKDF2_ROOT` and/or `OPENJKMOTS_ROOT` to override the search heuristics entirely, but by default it goes to the cwd (if an install is found) or `$XDG_DATA_HOME`, which Flatpak sandboxes. Currently there's no way to separate the controls/player/config JSONs though aside from symlinks.
